// <auto-generated />
using System;
using DataAccess.Concrete.EntityFramework.Contexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataAccess.Migrations {
    [DbContext (typeof (NorthwindContext))]
    [Migration ("20191115215357_InitialCreate")]
    partial class InitialCreate {
        protected override void BuildTargetModel (ModelBuilder modelBuilder) {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation ("ProductVersion", "3.0.0")
                .HasAnnotation ("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity ("Core.Entities.Concrete.OperationClaim", b => {
                b.Property<int> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("integer")
                    .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string> ("Name")
                    .HasColumnType ("text");

                b.HasKey ("Id");

                b.ToTable ("OperationClaims");
            });

            modelBuilder.Entity ("Core.Entities.Concrete.User", b => {
                b.Property<int> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("integer")
                    .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string> ("Email")
                    .HasColumnType ("text");

                b.Property<string> ("FirstName")
                    .HasColumnType ("text");

                b.Property<string> ("LastName")
                    .HasColumnType ("text");

                b.Property<byte[]> ("PasswordHash")
                    .HasColumnType ("bytea");

                b.Property<byte[]> ("PasswordSalt")
                    .HasColumnType ("bytea");

                b.Property<bool> ("Status")
                    .HasColumnType ("boolean");

                b.HasKey ("Id");

                b.ToTable ("Users");
            });

            modelBuilder.Entity ("Core.Entities.Concrete.UserOperationClaim", b => {
                b.Property<int> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("integer")
                    .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int> ("OperationClaimId")
                    .HasColumnType ("integer");

                b.Property<int> ("UserId")
                    .HasColumnType ("integer");

                b.HasKey ("Id");

                b.ToTable ("UserOperationClaims");
            });

            modelBuilder.Entity ("Entities.Concrete.Category", b => {
                b.Property<int> ("CategoryId")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("integer")
                    .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string> ("CategoryName")
                    .HasColumnType ("text");

                b.HasKey ("CategoryId");

                b.ToTable ("Categories");
            });

            modelBuilder.Entity ("Entities.Concrete.Log", b => {
                b.Property<int> ("Id")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("integer")
                    .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<string> ("Audit")
                    .HasColumnType ("text");

                b.Property<DateTime> ("Date")
                    .HasColumnType ("timestamp without time zone");

                b.Property<string> ("LogDetail")
                    .HasColumnType ("text");

                b.HasKey ("Id");

                b.ToTable ("Logs");
            });

            modelBuilder.Entity ("Entities.Concrete.Product", b => {
                b.Property<int> ("ProductID")
                    .ValueGeneratedOnAdd ()
                    .HasColumnType ("integer")
                    .HasAnnotation ("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                b.Property<int> ("CategoryId")
                    .HasColumnType ("integer");

                b.Property<string> ("ProductName")
                    .HasColumnType ("text");

                b.Property<string> ("QuantityPerUnit")
                    .HasColumnType ("text");

                b.Property<decimal> ("UnitPrice")
                    .HasColumnType ("numeric");

                b.Property<short> ("UnitsInStock")
                    .HasColumnType ("smallint");

                b.HasKey ("ProductID");

                b.ToTable ("Products");
            });
#pragma warning restore 612, 618
        }
    }
}